[project]
name = "rtoml Demo"
version = "3.0.0"
authors = ["Alice <alice@example.com>", "Bob <bob@example.com>"]

[database]
url = "postgresql://user:pass@localhost/db"
timeout = 30

[dependencies]
new = ["rtoml>=0.9.0", "requests>=2.28.0"]
